### ISSUE TITLE
Add configuration option to ignore SHAs from a list file

### ISSUE THREAD

**Issue by schoetbi** [orhun/git-cliff#390] opened 2023-12-18 09:43 UTC
The need for this feature comes mainly because sometimes commits should not alter the release notes. This can happen, for example, when a commit was reverted or when the format of a commit is not correct. 

The release notes are then not correct because in the first case the reverted commit is still in the release notes and in the second case things like e.g. the issue number might be missing.

To correct these erroneous commits, I suggest having a list of SHAs that are ignored during release notes generation. This is orthogonal to the skip feature in the commit_parser configuration. Maybe in the long run, it makes sense to split the skipping from the grouping. 

Given the following configuration where some parsers define grouping, others define skipping

```toml
commit_parsers = [
  # skips need to be first
  { message = "^[Tt]ask", skip = true },
  { sha = "f6f2472bdf0bbb5f9fcaf2d72c1fa9f98f772bb2", skip = true }, # see #385

  { message = "^[Ff]eat(ure)?", group = "Feature" },
  { message = "^([Bb]ug(fix)?|[Ff]ix)", group = "Bug" }, 
  { message = "^[Ee]xc(eption)?", group = "Exception" },
  { message = "^[Ii]mp(rovement)?", group = "Improvement" },
  { message = "^[Dd]oc(umentation)?", group = "Documentation" },
  { message = "^[Uu]sability", group = "Usability" },
  { message = "^[Ss]tyle|codequality", group = "Codequality" },
  { message = "^[Tt]est", group = "Testing" }, 
]
```
This could be changed to:

```toml
skip_parsers = [
  { message = "^[Tt]ask" },
  { sha = "f6f2472bdf0bbb5f9fcaf2d72c1fa9f98f772bb2" }, # see #385
  # many more shas
]
group_parsers = [
  { message = "^[Ff]eat(ure)?", group = "Feature" },
  { message = "^([Bb]ug(fix)?|[Ff]ix)", group = "Bug" },
  { message = "^[Ee]xc(eption)?", group = "Exception" },
  { message = "^[Ii]mp(rovement)?", group = "Improvement" },
  { message = "^[Dd]oc(umentation)?", group = "Documentation" },
  { message = "^[Uu]sability", group = "Usability" },
  { message = "^[Ss]tyle|codequality", group = "Codequality" },
  { message = "^[Tt]est", group = "Testing" },
]
```

In cases where the list of skips is very big it could make sense to read the shas from a skip_list:

```toml
skip_sha_file = ".git_cliff_ignore"
skip_parsers = [
  { message = "^[Tt]ask"},
  { sha = "f6f2472bdf0bbb5f9fcaf2d72c1fa9f98f772bb2"}, # see #385
 # ... many more shas
]
```

```
// .git_cliff_ignore
f6f2472bdf0bbb5f9fcaf2d72c1fa9f98f772bb2
... many more
```

As an extension, it could also help to skip commits by passing a command line option. Either by providing a sha one by one or by providing the ignore file as a parameter.

```
git cliff --skip f6f2472b --skip fffff release/1.2.3..release/1.2.4
git cliff --skip @.git_cliff_ignore release/1.2.3..release/1.2.4
```

**Comment by alerque** [comment] 2023-12-18 10:14
This is largely a duplicate of #382 and more specifically already being addressed in #385.

**Comment by schoetbi** [comment] 2023-12-18 11:29
@alerque yes, in wanted to explain the need for the new feature (list based skip). @orhun suggested creating a new ticket for that. https://github.com/orhun/git-cliff/pull/385#issuecomment-1858307298

**Comment by alerque** [comment] 2023-12-18 11:53
No no follow Orhun's directions here! Sorry I didn't realize this was being discussed as a variation already because I hadn't followed that whole thread, only know that it existed. The issue links are only useful for cross reference then, it isn't a duplicate.

**Comment by orhun** [comment] 2023-12-18 22:53
I really like this suggestion (especially separating the group/skip parsers) and I think I will implement it for the next release. A couple of things to clarify:

- For the ignore file, I would say let's go with `.cliffignore` as default for consistency with other tools (`.gitignore`, `.lycheeignore`). I'm not sure if making this configurable is useful since people often do not have custom names for ignore files.

- Instead of `--skip` we can use `--skip-commit` which might be more explanatory. Also, it doesn't need to take a file argument if we only support `.cliffignore`.

What do you think?

**Comment by schoetbi** [comment] 2023-12-19 06:58
@orhun I agree with your naming suggestions, these are more consistent. The idea to separate skip and group parsers could also help to first skip all the commits that match any skip parser and afterward group them with the help of the group parsers.

**Comment by orhun** [comment] 2023-12-27 18:58
I implemented the 2nd part of this issue in this PR: #413

When it comes to your first suggestion (`skip_parsers`), I thought about it and the only benefit is that `skip = true` is removed. The rest (commit parsers) stays pretty much the same so I decided to not implement it for now.

**Closed** 2023-12-31 14:34 UTC
Labels: feature/request

**Comment by schoetbi** [comment] 2024-01-10 16:43
Both features work great (`.cliffignore` and `--skip-commit`). Thank you for implementing this.

**Comment by orhun** [comment] 2024-01-10 21:22
Thank you for testing!
