### ISSUE TITLE
[gitlab] context data are missing

### ISSUE THREAD

**Issue by marcaurele** [orhun/git-cliff#801] opened 2024-08-18 16:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Description of the bug

When using the GitLab integration feature, the `gitlab` block in the contextual data is empty from all its information. Therefore the username handle, nor the MR number is available to create useful links in the changelog.

_Relates to #687_

### Steps To Reproduce

Configure `cliff.toml` as described for the Gitlab integration at https://git-cliff.org/docs/integration/gitlab

### Expected behavior

The context data should contain:
- the technical username usable with `@` handle
- the MR number related to the commit under `pr_number`
- the MR title under `pr_title`
- the MR labels under `pr_labels`

### Screenshots / Logs

Content is truncated / redacted to hide some information:

```console
$ git-cliff --context --unreleased
```

```json
[
  {
    "version": null,
    "message": null,
    "commits": [
      {
        "id": "e3b4e5149e42fae29589e00e27e8e05cbc0532c5",
        "message": "update dependency sentry-sdk to ~=2.12.0",
        "body": null,
        "footers": [
          {
            "token": "Changelog",
            "separator": ":",
            "value": "dependencies",
            "breaking": false
          }
        ],
        "group": "Bug Fixes",
        "breaking_description": null,
        "breaking": false,
        "scope": "deps",
        "links": [],
        "author": {
          "name": "Firstname Lastname",
          "email": "my.email@example.com",
          "timestamp": 1723374230
        },
        "committer": {
          "name": "Firstname Lastname",
          "email": "my.email@example.com",
          "timestamp": 1723374230
        },
        "conventional": true,
        "merge_commit": false,

        "gitlab": {
          "username": null,
          "pr_title": null,
          "pr_number": null,
          "pr_labels": [],
          "is_first_time": false
        },
        ...
      },
      ...
```

### Software information

- Operating system: Linux Debian
- Project version: `2.4.0`

### Additional context

This relates to the comment:

- https://github.com/orhun/git-cliff/issues/687#issuecomment-2220515751
- https://github.com/orhun/git-cliff/issues/687#issuecomment-2254367874 

I thought it would be easier to start another issue. Feel free to close that one @orhun if you prefer.

**Comment by orhun** [comment] 2024-08-18 17:54
I think it would make more sense to continue in #687 since it has more history about the cause and fix for this problem. 

I hope @tonybutt enlightens us about his fix in https://github.com/orhun/git-cliff/issues/687#issuecomment-2209092225 soon :)

**Closed** 2024-08-18 18:54 UTC
Labels: bug
